# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
## Customize the test machine
version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      environment:
        ANDROID_TARGET: android-23
        ADB_INSTALL_TIMEOUT: 12
        ANDROID_HOME: /usr/local/android-sdk-linux ./gradlew dependencies

    java:
        version: oraclejdk8

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test
